language: python
services:
  - postgresql
before_script:
  - psql -c 'create database app' -U postgres
install:
  - pip install -r requirements.txt
script:
  - flask db upgrade
  - pytest --junitxml=test-results/junit.xml --html=test-results/report.html