version: 2.1

orbs:
  python: circleci/python:3.8

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
  test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pytest
          name: Test


workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
