"""evenements

Revision ID: 00aec7ff36e9
Revises: 4160480fa180
Create Date: 2020-06-12 00:32:25.283261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00aec7ff36e9'
down_revision = '4160480fa180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evenement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titer', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('createur', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['createur'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evenement_date'), 'evenement', ['date'], unique=False)
    op.create_table('inscription',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('evenement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscription')
    op.drop_index(op.f('ix_evenement_date'), table_name='evenement')
    op.drop_table('evenement')
    # ### end Alembic commands ###
