"""Creat conversation for one event

Revision ID: 32dc58340f0f
Revises: c2dac782b42c
Create Date: 2020-06-14 20:46:10.145045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32dc58340f0f'
down_revision = 'c2dac782b42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('autheur', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['autheur'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_date'), 'message', ['date'], unique=False)
    op.create_table('discution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evenemnt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evenemnt_id'], ['evenement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discution')
    op.drop_index(op.f('ix_message_date'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
