"""followers validation

Revision ID: 4cbaf54ba6e7
Revises: 303f33b88c7a
Create Date: 2020-06-14 12:11:39.924384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbaf54ba6e7'
down_revision = '303f33b88c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('valider', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'valider')
    # ### end Alembic commands ###
