"""Update evenements

Revision ID: 6a321b495e8f
Revises: 00aec7ff36e9
Create Date: 2020-06-12 11:45:34.027178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a321b495e8f'
down_revision = '00aec7ff36e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evenement', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('evenement', sa.Column('titre', sa.String(), nullable=True))
    op.drop_column('evenement', 'titer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evenement', sa.Column('titer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('evenement', 'titre')
    op.drop_column('evenement', 'description')
    # ### end Alembic commands ###
