"""fix conversation for one event

Revision ID: afcb02eb2780
Revises: 32dc58340f0f
Create Date: 2020-06-14 20:49:41.976897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afcb02eb2780'
down_revision = '32dc58340f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('discution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'discution', ['discution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'discution_id')
    # ### end Alembic commands ###
