"""add request follow liste

Revision ID: b51ad3ed5802
Revises: 4cbaf54ba6e7
Create Date: 2020-06-14 14:32:38.387161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51ad3ed5802'
down_revision = '4cbaf54ba6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.Column('demande', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.drop_column('followers', 'valider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('valider', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('request_followers')
    # ### end Alembic commands ###
