"""update request follow liste

Revision ID: c2dac782b42c
Revises: b51ad3ed5802
Create Date: 2020-06-14 15:06:27.732722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dac782b42c'
down_revision = 'b51ad3ed5802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_followers', 'demande')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_followers', sa.Column('demande', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
