"""fix autheur field

Revision ID: c6291593df36
Revises: afcb02eb2780
Create Date: 2020-06-15 22:57:52.035181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6291593df36'
down_revision = 'afcb02eb2780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('author', sa.Integer(), nullable=True))
    op.drop_constraint('message_autheur_fkey', 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['author'], ['id'])
    op.drop_column('message', 'autheur')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('autheur', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key('message_autheur_fkey', 'message', 'user', ['autheur'], ['id'])
    op.drop_column('message', 'author')
    # ### end Alembic commands ###
