"""Update evenement

Revision ID: dcaaa4f9dac8
Revises: 6a321b495e8f
Create Date: 2020-06-12 21:09:46.717401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcaaa4f9dac8'
down_revision = '6a321b495e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evenement', sa.Column('isprivate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evenement', 'isprivate')
    # ### end Alembic commands ###
